name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  # Lint and format check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: |
          luacheck lua/ --globals vim --std luajit --codes || true

  # Unit tests
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim-version: ["stable", "nightly"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beancount

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      - name: Verify Neovim installation
        run: |
          echo "Neovim version:"
          nvim --version
          echo "Neovim location:"
          which nvim

      - name: Run all tests
        env:
          CI: true
          GITHUB_ACTIONS: true
          XDG_CONFIG_HOME: /tmp/empty
          XDG_DATA_HOME: /tmp/empty
        run: |
          # Create empty config directory to prevent any config loading
          mkdir -p /tmp/empty
          echo "Running test suite..."
          make test
