name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: ["stable", "nightly"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      - name: Verify Neovim installation
        run: |
          nvim --version
          which nvim

      - name: Run tests
        env:
          CI: true
          GITHUB_ACTIONS: true
          XDG_CONFIG_HOME: /tmp/empty
          XDG_DATA_HOME: /tmp/empty
        run: |
          # Create empty config directory to prevent any config loading
          mkdir -p /tmp/empty
          # Run tests with minimal environment
          make test

      - name: Test specific modules (if main tests fail)
        if: failure()
        env:
          CI: true
          GITHUB_ACTIONS: true
          XDG_CONFIG_HOME: /tmp/empty
          XDG_DATA_HOME: /tmp/empty
        run: |
          echo "Running individual test modules for debugging..."
          nvim --headless --noplugin --clean -c "luafile tests/config_test.lua" || echo "Config tests failed"
          nvim --headless --noplugin --clean -c "luafile tests/fold_test.lua" || echo "Fold tests failed"
          nvim --headless --noplugin --clean -c "luafile tests/inlay_hints_test.lua" || echo "Inlay hints tests failed"
          nvim --headless --noplugin --clean -c "luafile tests/navigation_test.lua" || echo "Navigation tests failed"
          nvim --headless --noplugin --clean -c "luafile tests/symbols_test.lua" || echo "Symbols tests failed"
          nvim --headless --noplugin --clean -c "luafile tests/utils_test.lua" || echo "Utils tests failed"
